version: '3.8'

services:
  db:
    image: postgres:13
    container_name: mypostgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose port for external access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  weather_collector:
    build:
      context: .  # Path to your Dockerfile
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: mypostgres
      DATABASE_PORT: 5432
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: password

